version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: arjun
      MYSQL_DATABASE: EmployeeDb
    ports:
      - "3310:3306"
    volumes:
      - dbdata:/var/lib/mysql

  task7:
    build:
      context: ./task7   # Folder containing Dockerfile and task7.csproj
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=server=db;port=3306;database=EmployeeDb;user=root;password=yourpassword

volumes:
  dbdata:
